### POST Book and return total time
POST {{host}}/api/book
Content-Type: application/json

< ../templates/bookCar.json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### POST Drive cars on one time unit
POST {{host}}/api/tick
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### PUT Reset all cars
PUT {{host}}/api/reset
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
